# Platform definitions sourced from Sherlock project (MIT/GPL) + custom additions.
# errorType:
#   status_code  - 200 = taken, 404 = available
#   message      - errorMsg present in body = NOT taken (user missing)
#   response_url - errorUrl in final URL = NOT taken (redirected away)

SITES = {

    # ── SOCIAL MEDIA ─────────────────────────────────────────────────────────
    "Twitter / X": {
        "url": "https://x.com/{}",
        "urlMain": "https://x.com",
        "category": "Social",
        "errorType": "status_code",
    },
    "Instagram": {
        "url": "https://www.instagram.com/{}",
        "urlMain": "https://www.instagram.com",
        "category": "Social",
        "errorType": "status_code",
    },
    "TikTok": {
        "url": "https://www.tiktok.com/@{}",
        "urlMain": "https://www.tiktok.com",
        "category": "Social",
        "errorType": "message",
        "errorMsg": "\"statusCode\":10221",
    },
    "LinkedIn": {
        "url": "https://www.linkedin.com/in/{}",
        "urlMain": "https://www.linkedin.com",
        "category": "Social",
        "errorType": "status_code",
    },
    "Reddit": {
        "url": "https://www.reddit.com/user/{}",
        "urlMain": "https://www.reddit.com",
        "category": "Social",
        "errorType": "message",
        "errorMsg": "Sorry, nobody on Reddit goes by that name",
    },
    "Pinterest": {
        "url": "https://www.pinterest.com/{}",
        "urlMain": "https://www.pinterest.com",
        "category": "Social",
        "errorType": "status_code",
    },
    "Snapchat": {
        "url": "https://www.snapchat.com/add/{}",
        "urlMain": "https://www.snapchat.com",
        "category": "Social",
        "errorType": "status_code",
    },
    "Bluesky": {
        "url": "https://bsky.app/profile/{}.bsky.social",
        "urlMain": "https://bsky.app",
        "category": "Social",
        "errorType": "status_code",
    },
    "Mastodon Social": {
        "url": "https://mastodon.social/@{}",
        "urlMain": "https://mastodon.social",
        "category": "Social",
        "errorType": "status_code",
    },
    "Mastodon Cloud": {
        "url": "https://mastodon.cloud/@{}",
        "urlMain": "https://mastodon.cloud",
        "category": "Social",
        "errorType": "status_code",
    },
    "Tumblr": {
        "url": "https://{}.tumblr.com",
        "urlMain": "https://www.tumblr.com",
        "category": "Social",
        "errorType": "status_code",
    },
    "Flipboard": {
        "url": "https://flipboard.com/@{}",
        "urlMain": "https://flipboard.com",
        "category": "Social",
        "errorType": "status_code",
    },
    "9GAG": {
        "url": "https://www.9gag.com/u/{}",
        "urlMain": "https://www.9gag.com",
        "category": "Social",
        "errorType": "status_code",
    },
    "BuzzFeed": {
        "url": "https://buzzfeed.com/{}",
        "urlMain": "https://buzzfeed.com",
        "category": "Social",
        "errorType": "status_code",
    },
    "Vero": {
        "url": "https://vero.co/{}",
        "urlMain": "https://vero.co",
        "category": "Social",
        "errorType": "message",
        "errorMsg": "Not Found",
    },

    # ── DEVELOPER & CODING ───────────────────────────────────────────────────
    "GitHub": {
        "url": "https://github.com/{}",
        "urlMain": "https://github.com",
        "category": "Developer",
        "errorType": "status_code",
    },
    "GitLab": {
        "url": "https://gitlab.com/{}",
        "urlMain": "https://gitlab.com",
        "category": "Developer",
        "errorType": "response_url",
        "errorUrl": "users/sign_in",
    },
    "Bitbucket": {
        "url": "https://bitbucket.org/{}/",
        "urlMain": "https://bitbucket.org",
        "category": "Developer",
        "errorType": "status_code",
    },
    "Codeberg": {
        "url": "https://codeberg.org/{}",
        "urlMain": "https://codeberg.org",
        "category": "Developer",
        "errorType": "status_code",
    },
    "Gitea": {
        "url": "https://gitea.com/{}",
        "urlMain": "https://gitea.com",
        "category": "Developer",
        "errorType": "status_code",
    },
    "Gitee": {
        "url": "https://gitee.com/{}",
        "urlMain": "https://gitee.com",
        "category": "Developer",
        "errorType": "status_code",
    },
    "HackerNews": {
        "url": "https://news.ycombinator.com/user?id={}",
        "urlMain": "https://news.ycombinator.com",
        "category": "Developer",
        "errorType": "message",
        "errorMsg": "No such user.",
    },
    "Dev.to": {
        "url": "https://dev.to/{}",
        "urlMain": "https://dev.to",
        "category": "Developer",
        "errorType": "status_code",
    },
    "CodePen": {
        "url": "https://codepen.io/{}",
        "urlMain": "https://codepen.io",
        "category": "Developer",
        "errorType": "status_code",
    },
    "Replit": {
        "url": "https://replit.com/@{}",
        "urlMain": "https://replit.com",
        "category": "Developer",
        "errorType": "status_code",
    },
    "LeetCode": {
        "url": "https://leetcode.com/{}",
        "urlMain": "https://leetcode.com",
        "category": "Developer",
        "errorType": "status_code",
    },
    "HackerRank": {
        "url": "https://hackerrank.com/{}",
        "urlMain": "https://hackerrank.com",
        "category": "Developer",
        "errorType": "message",
        "errorMsg": "Something went wrong",
    },
    "HackerEarth": {
        "url": "https://hackerearth.com/@{}",
        "urlMain": "https://hackerearth.com",
        "category": "Developer",
        "errorType": "status_code",
    },
    "Codeforces": {
        "url": "https://codeforces.com/profile/{}",
        "urlMain": "https://codeforces.com",
        "category": "Developer",
        "errorType": "status_code",
    },
    "Codewars": {
        "url": "https://www.codewars.com/users/{}",
        "urlMain": "https://www.codewars.com",
        "category": "Developer",
        "errorType": "status_code",
    },
    "NPM": {
        "url": "https://www.npmjs.com/~{}",
        "urlMain": "https://www.npmjs.com",
        "category": "Developer",
        "errorType": "status_code",
    },
    "PyPI": {
        "url": "https://pypi.org/user/{}/",
        "urlMain": "https://pypi.org",
        "category": "Developer",
        "errorType": "status_code",
    },
    "Docker Hub": {
        "url": "https://hub.docker.com/u/{}/",
        "urlMain": "https://hub.docker.com",
        "category": "Developer",
        "errorType": "status_code",
    },
    "SourceForge": {
        "url": "https://sourceforge.net/u/{}/profile/",
        "urlMain": "https://sourceforge.net",
        "category": "Developer",
        "errorType": "status_code",
    },
    "Kaggle": {
        "url": "https://www.kaggle.com/{}",
        "urlMain": "https://www.kaggle.com",
        "category": "Education",
        "errorType": "status_code",
    },
    "HuggingFace": {
        "url": "https://huggingface.co/{}",
        "urlMain": "https://huggingface.co",
        "category": "Developer",
        "errorType": "status_code",
    },
    "Wakatime": {
        "url": "https://wakatime.com/@{}",
        "urlMain": "https://wakatime.com",
        "category": "Developer",
        "errorType": "status_code",
    },
    "Hackster.io": {
        "url": "https://www.hackster.io/{}",
        "urlMain": "https://www.hackster.io",
        "category": "Developer",
        "errorType": "status_code",
    },
    "HackMD": {
        "url": "https://hackmd.io/@{}",
        "urlMain": "https://hackmd.io",
        "category": "Developer",
        "errorType": "status_code",
    },
    "Hashnode": {
        "url": "https://hashnode.com/@{}",
        "urlMain": "https://hashnode.com",
        "category": "Developer",
        "errorType": "status_code",
    },
    "Launchpad": {
        "url": "https://launchpad.net/~{}",
        "urlMain": "https://launchpad.net",
        "category": "Developer",
        "errorType": "status_code",
    },
    "RubyGems": {
        "url": "https://rubygems.org/profiles/{}",
        "urlMain": "https://rubygems.org",
        "category": "Developer",
        "errorType": "status_code",
    },
    "Codecademy": {
        "url": "https://www.codecademy.com/profiles/{}",
        "urlMain": "https://www.codecademy.com",
        "category": "Developer",
        "errorType": "message",
        "errorMsg": "This profile could not be found",
    },
    "CodeSandbox": {
        "url": "https://codesandbox.io/u/{}",
        "urlMain": "https://codesandbox.io",
        "category": "Developer",
        "errorType": "message",
        "errorMsg": "Could not find user with username",
    },
    "Crowdin": {
        "url": "https://crowdin.com/profile/{}",
        "urlMain": "https://crowdin.com",
        "category": "Developer",
        "errorType": "status_code",
    },

    # ── SECURITY / HACKING ───────────────────────────────────────────────────
    "HackerOne": {
        "url": "https://hackerone.com/{}",
        "urlMain": "https://hackerone.com",
        "category": "Security",
        "errorType": "message",
        "errorMsg": "Page not found",
    },
    "BugCrowd": {
        "url": "https://bugcrowd.com/{}",
        "urlMain": "https://bugcrowd.com",
        "category": "Security",
        "errorType": "status_code",
    },
    "TryHackMe": {
        "url": "https://tryhackme.com/p/{}",
        "urlMain": "https://tryhackme.com",
        "category": "Security",
        "errorType": "message",
        "errorMsg": "{\"success\":false}",
    },
    "HackTheBox": {
        "url": "https://forum.hackthebox.com/u/{}",
        "urlMain": "https://hackthebox.com",
        "category": "Security",
        "errorType": "status_code",
    },
    "PentesterLab": {
        "url": "https://pentesterlab.com/profile/{}",
        "urlMain": "https://pentesterlab.com",
        "category": "Security",
        "errorType": "status_code",
    },
    "VirusTotal": {
        "url": "https://www.virustotal.com/gui/user/{}",
        "urlMain": "https://www.virustotal.com",
        "category": "Security",
        "errorType": "status_code",
    },
    "Keybase": {
        "url": "https://keybase.io/{}",
        "urlMain": "https://keybase.io",
        "category": "Security",
        "errorType": "status_code",
    },

    # ── GAMING ───────────────────────────────────────────────────────────────
    "Twitch": {
        "url": "https://www.twitch.tv/{}",
        "urlMain": "https://www.twitch.tv",
        "category": "Gaming",
        "errorType": "status_code",
    },
    "Kick": {
        "url": "https://kick.com/{}",
        "urlMain": "https://kick.com",
        "category": "Gaming",
        "errorType": "status_code",
    },
    "Steam": {
        "url": "https://steamcommunity.com/id/{}/",
        "urlMain": "https://steamcommunity.com",
        "category": "Gaming",
        "errorType": "message",
        "errorMsg": "The specified profile could not be found",
    },
    "Roblox": {
        "url": "https://www.roblox.com/user.aspx?username={}",
        "urlMain": "https://www.roblox.com",
        "category": "Gaming",
        "errorType": "status_code",
    },
    "Chess.com": {
        "url": "https://www.chess.com/member/{}",
        "urlMain": "https://www.chess.com",
        "category": "Gaming",
        "errorType": "message",
        "errorMsg": "Username is valid",
    },
    "Lichess": {
        "url": "https://lichess.org/@/{}",
        "urlMain": "https://lichess.org",
        "category": "Gaming",
        "errorType": "status_code",
    },
    "Speedrun.com": {
        "url": "https://speedrun.com/users/{}",
        "urlMain": "https://speedrun.com",
        "category": "Gaming",
        "errorType": "status_code",
    },
    "Trovo": {
        "url": "https://trovo.live/s/{}/",
        "urlMain": "https://trovo.live",
        "category": "Gaming",
        "errorType": "message",
        "errorMsg": "Uh Ohhh",
    },
    "Minecraft": {
        "url": "https://api.mojang.com/users/profiles/minecraft/{}",
        "urlMain": "https://minecraft.net",
        "category": "Gaming",
        "errorType": "message",
        "errorMsg": "Couldn't find any profile",
    },
    "Star Citizen": {
        "url": "https://robertsspaceindustries.com/citizens/{}",
        "urlMain": "https://robertsspaceindustries.com",
        "category": "Gaming",
        "errorType": "message",
        "errorMsg": "404",
    },
    "Osu!": {
        "url": "https://osu.ppy.sh/users/{}",
        "urlMain": "https://osu.ppy.sh",
        "category": "Gaming",
        "errorType": "status_code",
    },
    "Scratch": {
        "url": "https://scratch.mit.edu/users/{}",
        "urlMain": "https://scratch.mit.edu",
        "category": "Gaming",
        "errorType": "status_code",
    },
    "Monkeytype": {
        "url": "https://monkeytype.com/profile/{}",
        "urlMain": "https://monkeytype.com",
        "category": "Gaming",
        "errorType": "status_code",
    },
    "Pokemon Showdown": {
        "url": "https://pokemonshowdown.com/users/{}",
        "urlMain": "https://pokemonshowdown.com",
        "category": "Gaming",
        "errorType": "status_code",
    },
    "FortniteTracker": {
        "url": "https://fortnitetracker.com/profile/all/{}",
        "urlMain": "https://fortnitetracker.com",
        "category": "Gaming",
        "errorType": "status_code",
    },
    "Runescape": {
        "url": "https://apps.runescape.com/runemetrics/app/overview/player/{}",
        "urlMain": "https://www.runescape.com",
        "category": "Gaming",
        "errorType": "message",
        "errorMsg": "NO_PROFILE",
    },
    "Nitro Type": {
        "url": "https://www.nitrotype.com/racer/{}",
        "urlMain": "https://www.nitrotype.com",
        "category": "Gaming",
        "errorType": "message",
        "errorMsg": "Nitro Type | Competitive Typing Game",
    },
    "TETR.IO": {
        "url": "https://ch.tetr.io/u/{}",
        "urlMain": "https://tetr.io",
        "category": "Gaming",
        "errorType": "message",
        "errorMsg": "No such user!",
    },
    "Warframe Market": {
        "url": "https://warframe.market/profile/{}",
        "urlMain": "https://warframe.market",
        "category": "Gaming",
        "errorType": "response_url",
        "errorUrl": "/error/404",
    },

    # ── CREATIVE ─────────────────────────────────────────────────────────────
    "Behance": {
        "url": "https://www.behance.net/{}",
        "urlMain": "https://www.behance.net",
        "category": "Creative",
        "errorType": "status_code",
    },
    "Dribbble": {
        "url": "https://dribbble.com/{}",
        "urlMain": "https://dribbble.com",
        "category": "Creative",
        "errorType": "message",
        "errorMsg": "Whoops, that page is gone.",
    },
    "ArtStation": {
        "url": "https://www.artstation.com/{}",
        "urlMain": "https://www.artstation.com",
        "category": "Creative",
        "errorType": "status_code",
    },
    "DeviantArt": {
        "url": "https://www.deviantart.com/{}",
        "urlMain": "https://www.deviantart.com",
        "category": "Creative",
        "errorType": "message",
        "errorMsg": "Llama Not Found",
    },
    "Flickr": {
        "url": "https://www.flickr.com/people/{}",
        "urlMain": "https://www.flickr.com",
        "category": "Creative",
        "errorType": "status_code",
    },
    "Vimeo": {
        "url": "https://vimeo.com/{}",
        "urlMain": "https://vimeo.com",
        "category": "Creative",
        "errorType": "status_code",
    },
    "SoundCloud": {
        "url": "https://soundcloud.com/{}",
        "urlMain": "https://soundcloud.com",
        "category": "Creative",
        "errorType": "status_code",
    },
    "Bandcamp": {
        "url": "https://www.bandcamp.com/{}",
        "urlMain": "https://www.bandcamp.com",
        "category": "Creative",
        "errorType": "status_code",
    },
    "Spotify": {
        "url": "https://open.spotify.com/user/{}",
        "urlMain": "https://open.spotify.com",
        "category": "Creative",
        "errorType": "status_code",
    },
    "Mixcloud": {
        "url": "https://www.mixcloud.com/{}/",
        "urlMain": "https://www.mixcloud.com",
        "category": "Creative",
        "errorType": "status_code",
    },
    "ReverbNation": {
        "url": "https://www.reverbnation.com/{}",
        "urlMain": "https://www.reverbnation.com",
        "category": "Creative",
        "errorType": "message",
        "errorMsg": "Sorry, we couldn't find that page",
    },
    "Redbubble": {
        "url": "https://www.redbubble.com/people/{}",
        "urlMain": "https://www.redbubble.com",
        "category": "Creative",
        "errorType": "status_code",
    },
    "Sketchfab": {
        "url": "https://sketchfab.com/{}",
        "urlMain": "https://sketchfab.com",
        "category": "Creative",
        "errorType": "status_code",
    },
    "Coroflot": {
        "url": "https://www.coroflot.com/{}",
        "urlMain": "https://coroflot.com",
        "category": "Creative",
        "errorType": "status_code",
    },
    "CGTrader": {
        "url": "https://www.cgtrader.com/{}",
        "urlMain": "https://www.cgtrader.com",
        "category": "Creative",
        "errorType": "status_code",
    },
    "VSCO": {
        "url": "https://vsco.co/{}",
        "urlMain": "https://vsco.co",
        "category": "Creative",
        "errorType": "status_code",
    },
    # EyeEm removed — acquired by Freepik, user profiles no longer exist
    "Freesound": {
        "url": "https://freesound.org/people/{}/",
        "urlMain": "https://freesound.org",
        "category": "Creative",
        "errorType": "status_code",
    },
    "Splice": {
        "url": "https://splice.com/{}",
        "urlMain": "https://splice.com",
        "category": "Creative",
        "errorType": "status_code",
    },

    # ── VIDEO ─────────────────────────────────────────────────────────────────
    "YouTube": {
        "url": "https://www.youtube.com/@{}",
        "urlMain": "https://www.youtube.com",
        "category": "Video",
        "errorType": "status_code",
    },
    "DailyMotion": {
        "url": "https://www.dailymotion.com/{}",
        "urlMain": "https://www.dailymotion.com",
        "category": "Video",
        "errorType": "status_code",
    },
    "Rumble": {
        "url": "https://rumble.com/user/{}",
        "urlMain": "https://rumble.com",
        "category": "Video",
        "errorType": "status_code",
    },
    "Odysee": {
        "url": "https://odysee.com/@{}",
        "urlMain": "https://odysee.com",
        "category": "Video",
        "errorType": "status_code",
    },

    # ── WRITING & BLOGS ──────────────────────────────────────────────────────
    "Medium": {
        "url": "https://medium.com/@{}",
        "urlMain": "https://medium.com",
        "category": "Writing",
        "errorType": "status_code",
    },
    "Letterboxd": {
        "url": "https://letterboxd.com/{}",
        "urlMain": "https://letterboxd.com",
        "category": "Entertainment",
        "errorType": "message",
        "errorMsg": "Sorry, we can’t find the page",
    },
    "Issuu": {
        "url": "https://issuu.com/{}",
        "urlMain": "https://issuu.com",
        "category": "Writing",
        "errorType": "status_code",
    },
    "HubPages": {
        "url": "https://hubpages.com/@{}",
        "urlMain": "https://hubpages.com",
        "category": "Writing",
        "errorType": "status_code",
    },
    "SlideShare": {
        "url": "https://slideshare.net/{}",
        "urlMain": "https://slideshare.net",
        "category": "Writing",
        "errorType": "message",
        "errorMsg": "Page no longer exists",
    },
    "Scribd": {
        "url": "https://www.scribd.com/{}",
        "urlMain": "https://www.scribd.com",
        "category": "Writing",
        "errorType": "message",
        "errorMsg": "Page not found",
    },
    "Archive of Our Own": {
        "url": "https://archiveofourown.org/users/{}",
        "urlMain": "https://archiveofourown.org",
        "category": "Writing",
        "errorType": "status_code",
    },
    "Wattpad": {
        "url": "https://www.wattpad.com/user/{}",
        "urlMain": "https://www.wattpad.com",
        "category": "Writing",
        "errorType": "status_code",
    },
    "GoodReads": {
        "url": "https://www.goodreads.com/{}",
        "urlMain": "https://www.goodreads.com",
        "category": "Writing",
        "errorType": "status_code",
    },

    # ── PROFESSIONAL ─────────────────────────────────────────────────────────
    "Product Hunt": {
        "url": "https://www.producthunt.com/@{}",
        "urlMain": "https://www.producthunt.com",
        "category": "Professional",
        "errorType": "status_code",
    },
    "Credly": {
        "url": "https://www.credly.com/users/{}",
        "urlMain": "https://www.credly.com",
        "category": "Professional",
        "errorType": "status_code",
    },
    "Academia.edu": {
        "url": "https://independent.academia.edu/{}",
        "urlMain": "https://www.academia.edu",
        "category": "Professional",
        "errorType": "status_code",
    },
    "Freelancer": {
        "url": "https://www.freelancer.com/u/{}",
        "urlMain": "https://www.freelancer.com",
        "category": "Professional",
        "errorType": "message",
        "errorMsg": "\"users\":{}",
    },
    "Coderwall": {
        "url": "https://coderwall.com/{}",
        "urlMain": "https://coderwall.com",
        "category": "Professional",
        "errorType": "status_code",
    },
    "OpenCollective": {
        "url": "https://opencollective.com/{}",
        "urlMain": "https://opencollective.com",
        "category": "Professional",
        "errorType": "status_code",
    },

    # ── SUPPORT / COMMUNITY ──────────────────────────────────────────────────
    "Patreon": {
        "url": "https://www.patreon.com/{}",
        "urlMain": "https://www.patreon.com",
        "category": "Community",
        "errorType": "status_code",
    },
    "Ko-fi": {
        "url": "https://ko-fi.com/{}",
        "urlMain": "https://ko-fi.com",
        "category": "Community",
        "errorType": "status_code",
    },
    "Buy Me a Coffee": {
        "url": "https://buymeacoffee.com/{}",
        "urlMain": "https://www.buymeacoffee.com",
        "category": "Community",
        "errorType": "status_code",
    },
    "Gumroad": {
        "url": "https://www.gumroad.com/{}",
        "urlMain": "https://www.gumroad.com",
        "category": "Community",
        "errorType": "message",
        "errorMsg": "Page not found (404) - Gumroad",
    },

    # ── MESSAGING / SOCIAL ───────────────────────────────────────────────────
    "Telegram": {
        "url": "https://t.me/{}",
        "urlMain": "https://t.me",
        "category": "Messaging",
        "errorType": "message",
        "errorMsg": "<title>Telegram Messenger</title>",
    },
    "Kik": {
        "url": "https://kik.me/{}",
        "urlMain": "https://kik.me",
        "category": "Messaging",
        "errorType": "message",
        "errorMsg": "The page you requested was not found",
    },

    # ── LINK IN BIO / PROFILE ────────────────────────────────────────────────
    "Linktree": {
        "url": "https://linktr.ee/{}",
        "urlMain": "https://linktr.ee",
        "category": "Profile",
        "errorType": "message",
        "errorMsg": "\"statusCode\":404",
    },
    "About.me": {
        "url": "https://about.me/{}",
        "urlMain": "https://about.me",
        "category": "Profile",
        "errorType": "status_code",
    },
    "Carrd": {
        "url": "https://{}.carrd.co/",
        "urlMain": "https://carrd.co",
        "category": "Profile",
        "errorType": "status_code",
    },
    "AllMyLinks": {
        "url": "https://allmylinks.com/{}",
        "urlMain": "https://allmylinks.com",
        "category": "Profile",
        "errorType": "message",
        "errorMsg": "Page not found",
    },
    "Gravatar": {
        "url": "https://en.gravatar.com/{}",
        "urlMain": "https://en.gravatar.com",
        "category": "Profile",
        "errorType": "status_code",
    },

    # ── FINANCE / PAYMENTS ───────────────────────────────────────────────────
    "Cash App": {
        "url": "https://cash.app/${}",
        "urlMain": "https://cash.app",
        "category": "Finance",
        "errorType": "status_code",
    },
    "Venmo": {
        "url": "https://account.venmo.com/u/{}",
        "urlMain": "https://venmo.com",
        "category": "Finance",
        "errorType": "message",
        "errorMsg": "Venmo | Page Not Found",
    },

    # ── LEARNING / EDUCATION ─────────────────────────────────────────────────
    "Duolingo": {
        "url": "https://www.duolingo.com/profile/{}",
        "urlMain": "https://duolingo.com",
        "category": "Education",
        "errorType": "message",
        "errorMsg": "{\"users\":[]}",
    },
    "Memrise": {
        "url": "https://www.memrise.com/user/{}/",
        "urlMain": "https://www.memrise.com",
        "category": "Education",
        "errorType": "status_code",
    },
    "GeeksforGeeks": {
        "url": "https://auth.geeksforgeeks.org/user/{}",
        "urlMain": "https://www.geeksforgeeks.org",
        "category": "Education",
        "errorType": "message",
        "errorMsg": "false   | GeeksforGeeks Profile",
    },
    # ── FORUMS / Q&A ─────────────────────────────────────────────────────────
    "Stack Overflow": {
        "url": "https://stackoverflow.com/users/{}",
        "urlMain": "https://stackoverflow.com",
        "category": "Forum",
        "errorType": "status_code",
    },
    "Slashdot": {
        "url": "https://slashdot.org/~{}",
        "urlMain": "https://slashdot.org",
        "category": "Forum",
        "errorType": "message",
        "errorMsg": "user you requested does not exist",
    },
    "Pastebin": {
        "url": "https://pastebin.com/u/{}",
        "urlMain": "https://pastebin.com",
        "category": "Forum",
        "errorType": "message",
        "errorMsg": "Not Found (#404)",
    },

    # ── ANIME / ENTERTAINMENT ────────────────────────────────────────────────
    "MyAnimeList": {
        "url": "https://myanimelist.net/profile/{}",
        "urlMain": "https://myanimelist.net",
        "category": "Entertainment",
        "errorType": "status_code",
    },
    "Anilist": {
        "url": "https://anilist.co/user/{}/",
        "urlMain": "https://anilist.co",
        "category": "Entertainment",
        "errorType": "status_code",
    },
    "Trakt": {
        "url": "https://www.trakt.tv/users/{}",
        "urlMain": "https://www.trakt.tv",
        "category": "Entertainment",
        "errorType": "status_code",
    },
    "Fandom": {
        "url": "https://www.fandom.com/u/{}",
        "urlMain": "https://www.fandom.com",
        "category": "Entertainment",
        "errorType": "status_code",
    },
    "GameFAQs": {
        "url": "https://gamefaqs.gamespot.com/community/{}",
        "urlMain": "https://gamefaqs.gamespot.com",
        "category": "Entertainment",
        "errorType": "status_code",
    },
    "Gamespot": {
        "url": "https://www.gamespot.com/profile/{}/",
        "urlMain": "https://www.gamespot.com",
        "category": "Entertainment",
        "errorType": "status_code",
    },
    "BoardGameGeek": {
        "url": "https://boardgamegeek.com/user/{}",
        "urlMain": "https://boardgamegeek.com",
        "category": "Entertainment",
        "errorType": "message",
        "errorMsg": "\"isValid\":true",
    },

    # ── MUSIC DISCOVERY ──────────────────────────────────────────────────────
    "Last.fm": {
        "url": "https://last.fm/user/{}",
        "urlMain": "https://last.fm",
        "category": "Music",
        "errorType": "status_code",
    },
    "Discogs": {
        "url": "https://www.discogs.com/user/{}",
        "urlMain": "https://www.discogs.com",
        "category": "Music",
        "errorType": "status_code",
    },

    # ── SPORTS / FITNESS ─────────────────────────────────────────────────────
    "Strava": {
        "url": "https://www.strava.com/athletes/{}",
        "urlMain": "https://www.strava.com",
        "category": "Sports",
        "errorType": "status_code",
    },
    "Untappd": {
        "url": "https://untappd.com/user/{}",
        "urlMain": "https://untappd.com",
        "category": "Sports",
        "errorType": "status_code",
    },
    "Geocaching": {
        "url": "https://www.geocaching.com/p/default.aspx?u={}",
        "urlMain": "https://www.geocaching.com",
        "category": "Sports",
        "errorType": "status_code",
    },

    # ── MISC ─────────────────────────────────────────────────────────────────
    "Wikipedia": {
        "url": "https://en.wikipedia.org/wiki/Special:CentralAuth/{}?uselang=qqx",
        "urlMain": "https://www.wikipedia.org",
        "category": "Misc",
        "errorType": "message",
        "errorMsg": "centralauth-admin-nonexistent:",
    },
    "Imgur": {
        "url": "https://imgur.com/user/{}",
        "urlMain": "https://imgur.com",
        "category": "Misc",
        "errorType": "status_code",
    },
    "Typeracer": {
        "url": "https://data.typeracer.com/pit/profile?user={}",
        "urlMain": "https://typeracer.com",
        "category": "Misc",
        "errorType": "message",
        "errorMsg": "Profile Not Found",
    },
    "TradingView": {
        "url": "https://www.tradingview.com/u/{}/",
        "urlMain": "https://www.tradingview.com",
        "category": "Misc",
        "errorType": "status_code",
    },
    "Giphy": {
        "url": "https://giphy.com/{}",
        "urlMain": "https://giphy.com",
        "category": "Misc",
        "errorType": "message",
        "errorMsg": "GIFs - Find &amp; Share",
    },
    "Houzz": {
        "url": "https://houzz.com/user/{}",
        "urlMain": "https://houzz.com",
        "category": "Misc",
        "errorType": "status_code",
    },
    "Instapaper": {
        "url": "https://www.instapaper.com/p/{}",
        "urlMain": "https://www.instapaper.com",
        "category": "Misc",
        "errorType": "status_code",
    },
    "OpenStreetMap": {
        "url": "https://www.openstreetmap.org/user/{}",
        "urlMain": "https://www.openstreetmap.org",
        "category": "Misc",
        "errorType": "status_code",
    },
    "Sporcle": {
        "url": "https://www.sporcle.com/user/{}/people",
        "urlMain": "https://www.sporcle.com",
        "category": "Misc",
        "errorType": "status_code",
    },
    "Couchsurfing": {
        "url": "https://www.couchsurfing.com/people/{}",
        "urlMain": "https://www.couchsurfing.com",
        "category": "Misc",
        "errorType": "status_code",
    },
    "Polarsteps": {
        "url": "https://polarsteps.com/{}",
        "urlMain": "https://polarsteps.com",
        "category": "Misc",
        "errorType": "status_code",
    },
    "Holopin": {
        "url": "https://holopin.io/@{}",
        "urlMain": "https://holopin.io",
        "category": "Misc",
        "errorType": "message",
        "errorMsg": "true",
    },
    "Pinkbike": {
        "url": "https://www.pinkbike.com/u/{}/",
        "urlMain": "https://www.pinkbike.com",
        "category": "Misc",
        "errorType": "status_code",
    },
    "Plurk": {
        "url": "https://www.plurk.com/{}",
        "urlMain": "https://www.plurk.com",
        "category": "Misc",
        "errorType": "message",
        "errorMsg": "User Not Found!",
    },
    "Smule": {
        "url": "https://www.smule.com/{}",
        "urlMain": "https://www.smule.com",
        "category": "Misc",
        "errorType": "message",
        "errorMsg": "Smule | Page Not Found (404)",
    },
}

CATEGORIES = sorted(set(s["category"] for s in SITES.values()))
